---
title           : "My preregistration for AsPredicted.org"
shorttitle      : "LDP Mini Project Bat Roosting Blanken Preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : First Author
    affiliation : 1
  - name        : Emma Blanken
    affiliation : "1"

affiliation:
  - id          : 1
    institution : University of Regina

output: prereg::prereg_pdf
bibliography: references.bib
---

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->

## Data collection

<!-- Have any data been collected for this study already? (Note: "Yes" is not an accepted answer.) -->

**Yes**, we already collected the data. The data that is considered in this mini project was collected in 2015 and 2016 in Ghana, West Africa. It was published in 2022. It considers the roosting behavior of the Gambian epauletted fruit bat (Epomophorus gambianus).

## Hypothesis

<!-- What's the main question being asked or hypothesis being tested in this study? -->

> The aim of this mini proect is to reproduce the results from the study with the data I am using. The authors found that roost choice is not random, and I expect in my data analysis to determine the same result.

## Dependent variable

<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

> The dependent variable of this study is roost location. It is determined using radiotelemetry, and once the roost structure is located measurements are taken such as: roost type, tree species, tree DBH, tree height, and other characeristics.

## Conditions

<!-- How many and which conditions will participants be assigned to? -->

> There are two condiitons in my basic analysis that roosts will be assigned to, occupied roost vs. random roost.

## Analyses

<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->

> I will use a t-test to compare the tree height, tree DBH, and tree crown diameter of occupied roosts vs random roosts to see if a true difference occurs.

## Outliers and exclusions

<!-- Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations. -->

> I will compute the overall mean and standard deviation across all conditions, and winsorize at 2.5 SD above/below the mean.

## Sample size

<!-- How many observations will be collected or what will determine sample size? No need to justify decision, but be precise about _exactly_ how the number will be determined. -->

> The data has been collected over October 2015 and February 2016. 60 bats were tagged and tracked total.

## Other

<!-- Anything else you would like to pre-register? (e.g., secondary analyses, variables collected for exploratory purposes, unusual analyses planned?) -->

## Study type

Finally. For record keeping purposes, please tell us the type of study you are pre-registering.

-   Observational

# References

## @amponsah-mensah2022

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
